name: FormsBot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: kon3gor <bboymishka888@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  teledart: ^0.0.36
  tripledes: ^2.1.0
  firedart: ^0.7.0
  gsheets: ^0.2.1+1
  http: ^0.12.0+4
  mailer2: ^1.2.5
